import React, { createContext, useContext, useState, useCallback, useMemo } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  EN: {
    home: 'HOME',
    latest: 'LATEST',
    ongoing: 'ONGOING',
    completed: 'COMPLETED',
    manage: 'MANAGE',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    searchPlaceholder: 'Search mangas, authors...',
    hotManga: 'HOT MANGA',
    latestReleases: 'LATEST RELEASES',
    viewAll: 'View All',
    readingHistory: 'Reading History',
    bookmarks: 'Bookmarks',
    genre: 'Genre',
    browse: 'Browse',
    noHistory: 'No history yet',
    noBookmarks: 'No bookmarks yet',
    continueAt: 'Continue at Ch.',
    backToStory: 'Back to Story',
    readFirstChapter: 'Read First Chapter',
    synopsis: 'Synopsis',
    chapters: 'Chapters',
    comments: 'Comments',
    newestFirst: 'Newest First',
    oldestFirst: 'Oldest First',
    search: 'Search',
    advancedSearch: 'Advanced Search',
    findNextFavorite: 'Find your next favorite manga using our comprehensive filters.',
    keywords: 'Keywords',
    allGenres: 'All Genres',
    allStatuses: 'All Statuses',
    sortBy: 'Sort By',
    latestUpdated: 'Latest Updated',
    newlyAdded: 'Newly Added',
    mostViewed: 'Most Viewed',
    az: 'A-Z',
    searchResults: 'Search Results',
    mangasFound: 'mangas found',
    mangaFound: 'manga found',
    noMatches: 'No matches found',
    tryAdjusting: 'Try adjusting your filters or search keywords.',
    clearFilters: 'Clear all filters',
    stories: 'Stories',
    users: 'Users',
    categories: 'Categories',
    hi: 'Hi',
    manageStories: 'Manage Stories',
    adminSubText: 'Manage story repository, add new, and edit details',
    editStory: 'Edit Story',
    createNewStory: 'Create New Story',
    title: 'Title',
    author: 'Author',
    status: 'Status',
    coverImageUrl: 'Cover Image URL',
    tipGoogleImages: "Tip: Paste a Google Images link and we'll extract the direct image URL for you.",
    saveUpdates: 'Save Updates',
    cancel: 'Cancel',
    createStory: 'Create Story',
    searchStoriesByName: 'Search stories by name...',
    story: 'Story',
    actions: 'Actions',
    noStoriesFound: 'No stories found',
    edit: 'Edit',
    delete: 'Delete',
    views_label: 'views',
    manageChapters: 'Manage Chapters',
    adminSubTextChapters: 'Manage content and ordering of story chapters',
    searchStory: 'Search Story',
    typeStoryName: 'Type story name...',
    editChapter: 'Edit Chapter',
    createNewChapter: 'Create New Chapter',
    chapterNumber: 'Chapter Number',
    chapterTitleOptional: 'Chapter Title (optional)',
    imageListUrls: 'Image List (URLs, separated by commas)',
    tipGoogleImagesShortened: 'Tip: Google Images links will be automatically shortened.',
    previewPages: 'Preview Pages',
    saveChapter: 'Save Chapter',
    addChapter: 'Add Chapter',
    chapterList: 'Chapter List',
    noChaptersPosted: 'No chapters posted yet',
    pages: 'pages',
    unknownAuthor: 'Unknown Author',
    manageUsers: 'Manage Users',
    adminSubTextUsers: 'Manage and update member permissions',
    addUser: 'Add User',
    searchByName: 'Search by name...',
    user: 'User',
    email: 'Email',
    role: 'Role',
    noUsersFound: 'No users found',
    adminRole: 'Admin',
    memberRole: 'Member',
    rename: 'Rename',
    changeRole: 'Change Role',
    manageCategories: 'Manage Categories',
    adminSubTextCategories_desc: 'Add, edit, and delete manga genres',
    categoryName: 'Category Name',
    slug_label: 'Slug',
    addNew: 'Add New',
    id_label: 'ID',
    noCategoriesFound: 'No categories found',
    manageComments: 'Manage Comments',
    adminSubTextComments_desc: 'Monitor and moderate community content',
    content: 'Content',
    target: 'Target',
    time: 'Time',
    noCommentsFound: 'No comments found',
    anonymous: 'Anonymous',
    quickLinks: 'Quick Links',
    ongoingSeries: 'Ongoing Series',
    completedSeries: 'Completed Series',
    connect: 'Connect'
  },
  VI: {
    home: 'TRANG CHỦ',
    latest: 'MỚI NHẤT',
    ongoing: 'ĐANG RA',
    completed: 'HOÀN THÀNH',
    manage: 'QUẢN LÝ',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    logout: 'Đăng xuất',
    searchPlaceholder: 'Tìm truyện, tác giả...',
    hotManga: 'TRUYỆN HOT',
    latestReleases: 'MỚI CẬP NHẬT',
    viewAll: 'Xem tất cả',
    readingHistory: 'Lịch sử đọc',
    bookmarks: 'Đánh dấu truyện',
    genre: 'Thể loại',
    browse: 'Khám phá',
    noHistory: 'Chưa có lịch sử',
    noBookmarks: 'Chưa có truyện theo dõi',
    continueAt: 'Đọc tiếp Ch.',
    backToStory: 'Quay lại truyện',
    readFirstChapter: 'Đọc chương đầu',
    synopsis: 'Nội dung',
    chapters: 'Chương',
    comments: 'Bình luận',
    newestFirst: 'Mới nhất',
    oldestFirst: 'Cũ nhất',
    search: 'Tìm kiếm',
    advancedSearch: 'Tìm kiếm nâng cao',
    findNextFavorite: 'Tìm bộ truyện yêu thích tiếp theo của bạn với bộ lọc của chúng tôi.',
    keywords: 'Từ khóa',
    allGenres: 'Tất cả thể loại',
    allStatuses: 'Tất cả trạng thái',
    sortBy: 'Sắp xếp theo',
    latestUpdated: 'Cập nhật mới nhất',
    newlyAdded: 'Truyện mới đăng',
    mostViewed: 'Xem nhiều nhất',
    az: 'A-Z (Tên)',
    searchResults: 'Kết quả tìm kiếm',
    mangasFound: 'truyện được tìm thấy',
    mangaFound: 'truyện được tìm thấy',
    noMatches: 'Không tìm thấy kết quả',
    tryAdjusting: 'Hãy thử điều chỉnh bộ lọc hoặc từ khóa tìm kiếm của bạn.',
    clearFilters: 'Xóa bộ lọc',
    stories: 'Truyện',
    users: 'Người dùng',
    categories: 'Thể loại',
    hi: 'Chào',
    manageStories: 'Quản lý truyện',
    adminSubText: 'Quản lý kho truyện, thêm mới và chỉnh sửa chi tiết',
    editStory: 'Chỉnh sửa truyện',
    createNewStory: 'Thêm truyện mới',
    title: 'Tiêu đề',
    author: 'Tác giả',
    status: 'Trạng thái',
    coverImageUrl: 'Đường dẫn ảnh bìa',
    tipGoogleImages: 'Mẹo: Dán link từ Google Images và chúng tôi sẽ tự động lấy link ảnh gốc cho bạn.',
    saveUpdates: 'Lưu cập nhật',
    cancel: 'Hủy',
    createStory: 'Tạo truyện',
    searchStoriesByName: 'Tìm truyện theo tên...',
    story: 'Truyện',
    actions: 'Hành động',
    noStoriesFound: 'Không tìm thấy truyện nào',
    edit: 'Sửa',
    delete: 'Xóa',
    views_label: 'lượt xem',
    manageChapters: 'Quản lý chương',
    adminSubTextChapters: 'Quản lý nội dung và thứ tự các chương truyện',
    searchStory: 'Tìm truyện',
    typeStoryName: 'Nhập tên truyện...',
    editChapter: 'Sửa chương',
    createNewChapter: 'Thêm chương mới',
    chapterNumber: 'Số chương',
    chapterTitleOptional: 'Tiêu đề chương (không bắt buộc)',
    imageListUrls: 'Danh sách ảnh (URL, cách nhau bằng dấu phẩy)',
    tipGoogleImagesShortened: 'Mẹo: Link từ Google Images sẽ được tự động rút gọn.',
    previewPages: 'Xem trước trang',
    saveChapter: 'Lưu chương',
    addChapter: 'Thêm chương',
    chapterList: 'Danh sách chương',
    noChaptersPosted: 'Chưa có chương nào được đăng',
    pages: 'trang',
    unknownAuthor: 'Không rõ tác giả',
    manageUsers: 'Quản lý người dùng',
    adminSubTextUsers: 'Quản lý và cập nhật quyền hạn thành viên',
    addUser: 'Thêm người dùng',
    searchByName: 'Tìm theo tên...',
    user: 'Người dùng',
    email: 'Email',
    role: 'Vai trò',
    noUsersFound: 'Không tìm thấy người dùng nào',
    adminRole: 'Quản trị viên',
    memberRole: 'Thành viên',
    rename: 'Đổi tên',
    changeRole: 'Đổi vai trò',
    manageCategories: 'Quản lý thể loại',
    adminSubTextCategories_desc: 'Thêm, sửa và xóa các thể loại truyện',
    categoryName: 'Tên thể loại',
    slug_label: 'Slug (Đường dẫn)',
    addNew: 'Thêm mới',
    id_label: 'ID',
    noCategoriesFound: 'Không tìm thấy thể loại nào',
    manageComments: 'Quản lý bình luận',
    adminSubTextComments_desc: 'Theo dõi và kiểm duyệt nội dung cộng đồng',
    content: 'Nội dung',
    target: 'Mục tiêu',
    time: 'Thời gian',
    noCommentsFound: 'Không tìm thấy bình luận nào',
    anonymous: 'Ẩn danh',
    quickLinks: 'Liên kết nhanh',
    ongoingSeries: 'Truyện đang ra',
    completedSeries: 'Truyện hoàn thành',
    connect: 'Liên kết'
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'EN');

  const toggleLang = useCallback(() => {
    setLang(prev => {
      const next = prev === 'EN' ? 'VI' : 'EN';
      localStorage.setItem('lang', next);
      return next;
    });
  }, []);

  const t = useCallback((key) => {
    return translations[lang][key] || key;
  }, [lang]);

  const value = useMemo(() => ({
    lang,
    toggleLang,
    t
  }), [lang, toggleLang, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
